#!/bin/sh

export \
	SPN_FUSDC_ADDR=0xaf88d065e77c8cC2239327C5EDb3A432268e5831 \
	SPN_STAKED_ARB_ADDR= \
	SPN_DAO_EARN_ADDR= \
	SPN_DAO_OP_ADDR= \
	SPN_SHARE_IMPL_ADDR= \
	SPN_CLAIMANT_HELPER_ADDR= \
	SPN_PAYMASTER_ADDR= \
	SPN_CAMELOT_SWAP_ROUTER= \
	SPN_CLAWBACK_RECIPIENT_ADDR= \
	SPN_TRADING_BEACON_ADDR= \
	SPN_VAULT_ADDR= \
	SPN_HOUR_DPPM_CREATOR= \
	SPN_15_MIN_DPPM_CREATOR= \
	SPN_5_MIN_DPPM_CREATOR= \
	SPN_ENCLAVE_ADDR=

make -B $@
