[package]
name = "ninelives"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"

[lib]
name = "lib9lives"
edition = "2021"

[[bin]]
name = "ninelives"

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[dependencies]
stylus-sdk = "0.5.2"
thiserror = "1.0.48"
tiny-keccak = "2.0.2"
num-traits = "0.2.19"
alloy-sol-types = "0.7.6"
alloy-sol-macro = "0.7.6"
lol_alloc = "0.4.0"
astro-float = { version = "0.9.4", default-features = false }
getrandom = { version = "0.2.15", features = ["js"] }
array-concat = "0.5.3"
sha3-const = "0.1.1"

[dev-dependencies]
const-hex = "1.12.0"
proptest = "1.5.0"

[features]
factory = []
trading = []
testing-dbg = []
