[package]
name = "ninelives"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"

[lib]
name = "lib9lives"
edition = "2021"

[[bin]]
name = "ninelives"

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[dependencies]
stylus-sdk = "0.6.0"
thiserror = "1.0.48"
tiny-keccak = "2.0.2"
num-traits = "0.2.19"
alloy-sol-types = "=0.7.6"
alloy-sol-macro = "=0.7.6"
astro-float = { version = "0.9.4", default-features = false }
getrandom = { version = "0.2.15", features = ["js"] }
array-concat = "0.5.3"
sha3-const = "0.1.1"
const-hex = { version = "1.12.0" }
paste = "1.0.15"

[dev-dependencies]
proptest = "1.5.0"
const-hex = { version = "1.12.0", features = ["alloc"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
alloy-primitives = { version = "0.7.6", features = ["getrandom"] }

[features]
factory = []
trading = []
testing-dbg = []
testing = []
