"use client";

import useReferrerCode from "@/hooks/useReferrerCode";
import LoadingIndicator from "../loadingIndicator";
import { Fragment, useEffect, useState } from "react";
import { useActiveAccount } from "thirdweb/react";
import Button from "../themed/button";
import { Tab, TabGroup, TabList, TabPanel, TabPanels } from "@headlessui/react";
import TabButton from "../tabButton";
import toast from "react-hot-toast";
import useConnectWallet from "@/hooks/useConnectWallet";

export default function RefereeDialog({ code }: { code: string }) {
  const account = useActiveAccount();
  const { connect } = useConnectWallet();
  const {
    data: sender,
    isSuccess,
    isError,
    error,
    isLoading,
  } = useReferrerCode(account?.address);
  const [inProgress, setInProgress] = useState(false);
  async function syncAndConfim() {
    toast.promise(
      new Promise(async (res, rej) => {
        try {
          if (!account) {
            await connect();
          }
          setInProgress(true);
          res(null);
        } catch (error) {
          rej(error);
        } finally {
          setInProgress(false);
        }
      }),
      {
        loading: "Loading...",
        success: "Referrer confirmed",
        error: "Confirmation failed",
      },
    );
  }

  if (isLoading)
    return (
      <div className="flex h-20 items-center justify-center">
        <LoadingIndicator />
      </div>
    );

  if (isError || (isSuccess && !sender))
    return (
      <div className="flex h-20 items-center justify-center">
        <p className="font-chicago">Ups something went wrong</p>
        <p className="text-xs">{error?.message ?? "Unknown error"}</p>
      </div>
    );

  return (
    <div className="mx-auto flex w-[70%] flex-col items-center justify-center gap-5 pb-8">
      <div className="flex flex-col items-center justify-center gap-2">
        <p className="font-geneva uppercase">You are referred by {code}</p>
      </div>
      <Button
        size={"xlarge"}
        disabled={inProgress}
        onClick={syncAndConfim}
        intent={"cta"}
        title={inProgress ? "Loading..." : "SIGN AND CONFIRM"}
        className="w-full"
      />
      <TabGroup className={"w-full"}>
        <TabList className={"flex items-center justify-center"}>
          <Tab as={Fragment}>
            {(props) => <TabButton title="How It Works" {...props} />}
          </Tab>
          <Tab as={Fragment} disabled>
            {(props) => <TabButton title="Fees Generated" {...props} />}
          </Tab>
        </TabList>
        <TabPanels>
          <TabPanel>
            <div className="w-full rounded-tl-none border border-9black bg-9gray p-3 shadow-9orderSummary md:p-5">
              <div className="flex flex-col items-center justify-center gap-4 font-chicago">
                <div className="flex items-center justify-between gap-4">
                  <div className="flex items-center gap-1 text-xs">
                    <div className="flex size-4 items-center justify-center gap-2 rounded-full border border-9black">
                      1
                    </div>
                    <span>Sign and confirm.</span>
                  </div>
                  <div className="flex items-center gap-1 text-xs">
                    <div className="flex size-4 items-center justify-center rounded-full border border-9black">
                      2
                    </div>
                    <span>Let your referrer earn</span>
                  </div>
                </div>
                <p className="bg-9green px-4 py-2 text-sm">
                  Referrer gets %1 of fees generated by you
                </p>
                <p className="text-xs text-9black/60">
                  You can create your own referral code to earn rewards!
                </p>
              </div>
            </div>
          </TabPanel>
        </TabPanels>
      </TabGroup>
    </div>
  );
}
