"use client";

import useReferrerCode from "@/hooks/useReferrerCode";
import LoadingIndicator from "../loadingIndicator";
import { Fragment, useEffect, useState } from "react";
import { genReferrer } from "@/providers/graphqlClient";
import { generateReferralCode } from "@/utils/generateReferralCode";
import { useActiveAccount } from "thirdweb/react";
import Button from "../themed/button";
import { Tab, TabGroup, TabList, TabPanel, TabPanels } from "@headlessui/react";
import TabButton from "../tabButton";

export default function ReferralDialog() {
  const {
    data: code,
    isSuccess,
    error,
    isLoading,
    refetch,
  } = useReferrerCode();
  const account = useActiveAccount();
  const [genError, setGenError] = useState<string>();
  async function generateCode() {
    try {
      if (!account?.address)
        throw new Error("Connect your wallet to generate a referral code");
      const code = generateReferralCode();
      await genReferrer({ address: account.address, code });
      await refetch();
    } catch (error) {
      setGenError(error instanceof Error ? error.message : "Unknown error");
    }
  }
  useEffect(() => {
    if (isSuccess && !code) {
      generateCode();
    }
  }, [code, isSuccess]);

  if (isLoading || (isSuccess && !code))
    return (
      <div className="flex h-20 items-center justify-center">
        <LoadingIndicator />
      </div>
    );

  if (code)
    return (
      <div className="flex flex-col items-center justify-center gap-4">
        <div className="flex flex-col items-center justify-center gap-2">
          <p className="font-geneva uppercase">You have 0 active referrals</p>
          <p className="text-xs text-9black/60">
            Refer users using your link to earn more rewards!
          </p>
        </div>
        <p className="border px-4 py-2">{`https://9lives.so/?referral=${code}`}</p>
        <Button intent={"cta"} title="COPY LINK" />
        <p className="font-chicago">
          Share To: <a className="font-geneva uppercase underline">TWITTER</a>
        </p>
        <TabGroup>
          <TabList>
            <Tab as={Fragment}>
              {(props) => <TabButton title="How It Works" {...props} />}
            </Tab>
            <Tab as={Fragment} disabled>
              {(props) => <TabButton title="Fees Generated" {...props} />}
            </Tab>
          </TabList>
          <TabPanels>
            <TabPanel>
              <div className="flex flex-col items-center justify-center gap-4">
                <div className="flex items-center">
                  <div className="flex items-center">
                    <div className="rounded-full border border-9black p-1 text-xs">
                      1
                    </div>
                    <span>Copy your link.</span>
                  </div>
                  <div className="flex items-center">
                    <div className="rounded-full border border-9black p-1 text-xs">
                      2
                    </div>
                    <span>Share with your friends.</span>
                  </div>
                  <p className="font-chicago text-sm">
                    You get %1 of fees generated by referred user
                  </p>
                </div>
              </div>
            </TabPanel>
          </TabPanels>
        </TabGroup>
      </div>
    );

  return (
    <div className="flex h-20 items-center justify-center">
      <p className="font-chicago">Ups something went wrong</p>
      <p className="text-xs">{error?.message ?? genError ?? "Unknown error"}</p>
    </div>
  );
}
