name: Deploy webapp

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: mainnet
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_THIRDWEB_ID: ${{ vars.NEXT_PUBLIC_THIRDWEB_ID }}
      NEXT_PUBLIC_GRAPHQL_URL: "https://testnet-graph.9lives.so"
      NEXT_PUBLIC_FEATURES_URL: "https://features.9lives.so/features.json"
      NEXT_PUBLIC_POINTS_URL: "https://points-graph.superposition.so"
      NEXT_PUBLIC_FUSDC_ADDR: "0xa8ea92c819463efbeddfb670fefc881a480f0115"
      NEXT_PUBLIC_AMM_ADDR: "0x2A4a912970b780C29cf5b97aaD45ea5f98A07341"
      NEXT_PUBLIC_FACTORY_ADDR: "0x048db37b4bf07744bca95498e078af490c7b66fd"
      NEXT_PUBLIC_LENS_ADDR: "0xe5d515eC8ECa5d70518e452b594dD0EFb715cB7d"
      NEXT_PUBLIC_HELPER_ADDR: "0x2790A6F7aA7679385Af917F06cFF0C0ff484F0d7"
      NEXT_PUBLIC_INFRA_ADDR: "0xbdce46aca28a05f969cf675cb2777bae23bd7ff8"
      NEXT_PUBLIC_AI_ADDR: "0x15bebdf285bfe0039fd266af207f6d278aaac7f3"
      NEXT_PUBLIC_BEAUTY_ADDR: "0x3f8cd5a3a67b57f8370c5699064e642d5924608b"
      NEXT_PUBLIC_POSTHOG_KEY: "phc_wFN8nVjgKYNURCUsE7MEFUdAjgKE6aDC01AAEXLUGyt"
      NEXT_PUBLIC_POSTHOG_HOST: "https://us.i.posthog.com"
      NEXT_PUBLIC_WS_URL: "wss://superposition-test.hasura.app/v1/graphql"
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"

      - uses: actions/setup-node@v3
        with:
           node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Build with Vercel
        run: vercel build --yes --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
