name: Deploy webapp

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './web'
    environment: mainnet
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_THIRDWEB_ID: ${{ vars.NEXT_PUBLIC_THIRDWEB_ID }}
      NEXT_PUBLIC_GRAPHQL_URL: "https://testnet-graph.9lives.so"
      NEXT_PUBLIC_FEATURES_URL: "https://features.9lives.so/features.json"
      NEXT_PUBLIC_FUSDC_ADDR: "0xa8ea92c819463efbeddfb670fefc881a480f0115"
      NEXT_PUBLIC_FACTORY_ADDR: "0x3A238B6b12F5da5ED7BAA7Fbb871fc5455AA2fc0"
      NEXT_PUBLIC_AMM_ADDR: "0xd706b85c571330af8495174664d04D6d8551F9D5"
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm
            ${{ github.workspace }}/.vercel
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest
              
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build with Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
