name: Deploy webapp

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: mainnet
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_THIRDWEB_ID: ${{ vars.NEXT_PUBLIC_THIRDWEB_ID }}
      NEXT_PUBLIC_GRAPHQL_URL: "https://graph.9lives.so"
      NEXT_PUBLIC_FEATURES_URL: "https://features.9lives.so/features.json"
      NEXT_PUBLIC_POINTS_URL: "https://points-graph.superposition.so"
      NEXT_PUBLIC_FUSDC_ADDR: "0x4cfa50b7ce747e2d61724fcac57f24b748ff2b2a"
      NEXT_PUBLIC_FACTORY_ADDR: "0x6c49d7845d1C9540B3D53B01296248b4B0a9d60D"
      NEXT_PUBLIC_AMM_ADDR: "0xe89E8Cb7E84Dd1b4460cF2a51B3f0B05Ff952bB6"
      NEXT_PUBLIC_LENS_ADDR: "0x30Cc3AbEcf76fd53dDf3103395B1Fc6eDA1d1599"
      NEXT_PUBLIC_POSTHOG_KEY: "phc_wFN8nVjgKYNURCUsE7MEFUdAjgKE6aDC01AAEXLUGyt"
      NEXT_PUBLIC_POSTHOG_HOST: "https://us.i.posthog.com"
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Build with Vercel
        run: vercel build --yes --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
