name: Deploy webapp (Arbitrum)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: mainnet
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ARB_PROJECT_ID }}
      NEXT_PUBLIC_WC_ID: ${{ vars.NEXT_PUBLIC_WC_ID }}
      NEXT_PUBLIC_GRAPHQL_URL: "https://9lives-arb.stellate.sh"
      NEXT_PUBLIC_FEATURES_URL: "https://features.9lives.so/features.json"
      NEXT_PUBLIC_POINTS_URL: "https://points-graph.superposition.so"
      NEXT_PUBLIC_ACCOUNTS_URL: "https://accounts.superposition.so/"
      NEXT_PUBLIC_FUSDC_ADDR: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
      NEXT_PUBLIC_AMM_ADDR: "0x0000000000000000000000000000000000000000"
      NEXT_PUBLIC_LENS_ADDR: "0xF0dd060f469A2445736Df0EAE97e24113faCe0d6"
      NEXT_PUBLIC_HELPER_FACTORY_ADDR: "0x263735150e8b48FF6bF471DB94f113e9994C333d"
      NEXT_PUBLIC_BUY_HELPER_ADDR: "0xAa901219528e22aC1E3a3bDc40a34Eab7983d240"
      NEXT_PUBLIC_INFRA_ADDR: "0x0000000000000000000000000000000000000000"
      NEXT_PUBLIC_AI_ADDR: "0xA2cFa0E8dD8abD255343c9ab6D36f3306Ad3A6aB"
      NEXT_PUBLIC_BEAUTY_ADDR: "0x0000000000000000000000000000000000000000"
      NEXT_PUBLIC_SARP_SIGNALLER_ADDR: "0xa81a0adab3492dae14c45c39d322a78a24c8b683"
      NEXT_PUBLIC_MEOW_DOMAINS_ADDR: "0x0000000000000000000000000000000000000000"
      NEXT_PUBLIC_POSTHOG_KEY: "phc_wFN8nVjgKYNURCUsE7MEFUdAjgKE6aDC01AAEXLUGyt"
      NEXT_PUBLIC_POSTHOG_HOST: "https://events.9lives.so"
      NEXT_PUBLIC_WS_URL: "wss://arb-websocket.9lives.so"
      NEXT_PUBLIC_CHAIN: "mainnet"
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      POSTHOG_ENV_ID: ${{ secrets.POSTHOG_ENV_ID }}
      NEXT_PUBLIC_SNITCH_ENDPOINT: "https://snitch.superposition.so"
      NEXT_PUBLIC_CLAIMANT_HELPER_ADDR: "0xf8Da8d65120b317331C79092Bf65e99bed6e65dE"
      NEXT_PUBLIC_BUY_HELPER2_ADDR: "0xf8Da8d65120b317331C79092Bf65e99bed6e65dE"
      NEXT_PUBLIC_PAYMASTER_ADDR: "0xA19B3a76d5744825c3672a5FFE1F4F5Aee3F28dE"
      NEXT_PUBLIC_ACCOUNT_AUTHORITY_ADDR: "0xa80AdFC480BdB9dB308999760Fec8fA567cdB87D"
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"

      - uses: actions/setup-node@v4
        with:
           node-version: 22.x

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Build Project Artifacts
        run: vercel build --yes --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --archive=tgz --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
